# Generated by Django 5.0.3 on 2024-03-25 07:31

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_challenge_encoded_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='file',
            field=models.FileField(upload_to=myapp.models.challenge_file_upload_path),
        ),
    ]
