# Generated by Django 5.0.3 on 2024-03-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_challenge_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='encoded_filename',
        ),
    ]
